import tweepy as tw

CONSUMER_KEY = "7N16dARDDawvLrwrODDVKyZdK"
CONSUMER_SECRET = "xWsfInRh1F2iFKQA2Qk5BktsRsb9pP8wyBiy9Tz7zSDk1ZjwuR"
ACCESS_TOKEN = "136652289-Pe5e1pUpqtn0gynEPNjIAyqYfq1WSRxtFubKQtGf"
ACCESS_TOKEN_SECRET = "7LLuWMTPaKQ9ZJwA5FQGkSobXHMi8JM2EfnXfyNvabunR"
AUTH = tw.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
AUTH.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
API = tw.API(AUTH, wait_on_rate_limit=True)
SEARCH_WORDS = "#covid19 -filter:retweets"
DATE_SINCE = "2020-03-01"